# Place a copy of this config to ~/.aerospace.toml
# After that, you can edit ~/.aerospace.toml to your liking

# You can use it to add commands that run after AeroSpace startup.
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = []

# Start AeroSpace at login
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 30

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
# Fallback value (if you omit the key): on-focused-monitor-changed = []
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# You can effectively turn off macOS "Hide application" (cmd-h) feature by toggling this flag
# Useful if you don't use this macOS feature, but accidentally hit cmd-h or cmd-alt-h key
# Also see: https://nikitabobko.github.io/AeroSpace/goodies#disable-hide-app
automatically-unhide-macos-hidden-apps = false

[workspace-to-monitor-force-assignment]
    1 = 1                            # Monitor sequence number from left to right. 1-based indexing
    2 = 'main'                       # Main monitor
    3 = 'secondary'                  # Non-main monitor in case when there are only two monitors
    4 = 'built-in'                   # Case insensitive regex substring
    5 = '^built-in retina display$'  # Case insensitive regex match
    6 = ['secondary', 'dell']        # You can specify multiple patterns.
                                     # The first matching pattern will be used
# Possible values: (qwerty|dvorak|colemak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
[key-mapping]
    preset = 'qwerty'

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See:
#                 https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
    inner.horizontal = 10
    inner.vertical =   10
    outer.left =       10
    outer.bottom =     10
    outer.top =        10
    outer.right =      10

# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
# Fallback value (if you omit the key): mode.main.binding = {}
[mode.main.binding]

    # All possible keys:
    # - Letters.        a, b, c, ..., z
    # - Numbers.        0, 1, 2, ..., 9
    # - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
    # - F-keys.         f1, f2, ..., f20
    # - Special keys.   minus(-), equal(=), period(.), comma(,), slash(/), backslash(\), quote('), semicolon(;),
    #                   backtick(`), leftSquareBracket([), rightSquareBracket(]), space( ), enter( ), esc( ), backspace(⌫), tab(⇥)
    #                   backspace, tab, pageUp, pageDown, home, end, forwardDelete,
    #                   sectionSign (ISO keyboards only, european keyboards only)
    # - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
    #                   keypadMinus, keypadMultiply, keypadPlus
    # - Arrows.         left, down, up, right

    # All possible modifiers: cmd, alt, ctrl, shift

    # All possible commands: https://nikitabobko.github.io/AeroSpace/commands

    # See: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget
    # You can uncomment the following lines to open up terminal with alt + enter shortcut
    # (like in i3)
    # alt-enter = '''exec-and-forget osascript -e '
    # tell application "Terminal"
    #     do script
    #     activate
    # end tell'
    # '''

    alt-space = ['mode alt']
    alt-a = ['mode edit-workspace']

    # See: https://nikitabobko.github.io/AeroSpace/commands#layout
    # alt-slash = 'layout tiles horizontal vertical'
    # alt-comma = 'layout accordion horizontal vertical'

    # See: https://nikitabobko.github.io/AeroSpace/commands#focus
    # alt-h = 'focus left'
    # alt-j = 'focus down'
    # alt-k = 'focus up'
    # alt-l = 'focus right'


    # See: https://nikitabobko.github.io/AeroSpace/commands#resize
    # alt-minus = 'resize smart -10'
    # alt-equal = 'resize smart +10'

    # See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
    # alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

    # See: https://nikitabobko.github.io/AeroSpace/commands#mode
    # alt-shift-semicolon = 'mode service'

# 'service' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# [mode.service.binding]
    # esc = ['reload-config', 'mode main']
    # r = ['flatten-workspace-tree', 'mode main'] # reset layout
    # f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
    # backspace = ['close-all-windows-but-current', 'mode main']

    # sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
    #s = ['layout sticky tiling', 'mode main']

    # alt-shift-h = ['join-with left', 'mode main']
    # alt-shift-j = ['join-with down', 'mode main']
    # alt-shift-k = ['join-with up', 'mode main']
    # alt-shift-l = ['join-with right', 'mode main']

    # down = 'volume down'
    # up = 'volume up'
    # shift-down = ['volume set 0', 'mode main']

[mode.alt.binding]

    # - Special keys.   minus(-), equal(=), period(.), comma(,), slash(/), backslash(\), quote('), semicolon(;),
    #                   backtick(`), leftSquareBracket([), rightSquareBracket(]), space( ), enter( ), esc( ), backspace(⌫), tab(⇥)

# ctrl-alt-cmd-space = ['mode main']
space = ['mode main']
esc = ['mode main']
backtick = ['reload-config', 'mode main']

# You can uncomment this line to open up terminal with alt + enter shortcut
# See: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget
alt-enter = 'exec-and-forget open -n /System/Applications/Utilities/Terminal.app'

# See: https://nikitabobko.github.io/AeroSpace/commands#layout
slash = 'layout horizontal vertical'
quote = 'layout tiles accordion'

#
# Navigation
#

# See: https://nikitabobko.github.io/AeroSpace/commands#focus
h = ['focus --boundaries-action stop left', 'move-mouse window-force-center']
j = ['focus --boundaries-action stop down', 'move-mouse window-force-center']
k = ['focus --boundaries-action stop up', 'move-mouse window-force-center']
l = ['focus --boundaries-action stop right', 'move-mouse window-force-center']
u = 'workspace prev'
i = 'workspace next'
p = ['focus-monitor prev', 'move-mouse window-force-center']
n = ['focus-monitor next', 'move-mouse window-force-center']

ctrl-alt-cmd-h = ['workspace prev']
ctrl-alt-cmd-l = ['workspace next']
ctrl-alt-cmd-k = ['focus-monitor prev', 'move-mouse window-force-center']
ctrl-alt-cmd-j = ['focus-monitor next', 'move-mouse window-force-center']

c = ['move-mouse window-force-center']

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
tab = ['workspace-back-and-forth', 'move-mouse window-force-center', 'mode main']
# See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
shift-tab = ['move-workspace-to-monitor --wrap-around next', 'move-mouse window-force-center', 'mode main']
#
# Moving
#

# See: https://nikitabobko.github.io/AeroSpace/commands#move
shift-h = 'move left'
shift-j = 'move down'
shift-k = 'move up'
shift-l = 'move right'
shift-u = 'move-node-to-workspace prev'
shift-i = 'move-node-to-workspace next'
shift-p = 'move-workspace-to-monitor prev'
shift-n = 'move-workspace-to-monitor next'
ctrl-alt-cmd-shift-h = ['move-node-to-workspace prev']
ctrl-alt-cmd-shift-l = ['move-node-to-workspace next']
ctrl-alt-cmd-shift-k = ['move-workspace-to-monitor prev']
ctrl-alt-cmd-shift-j = ['move-workspace-to-monitor next']

#
# Resizing
#

# See: https://nikitabobko.github.io/AeroSpace/commands#resize
minus = 'resize smart -64'
equal = 'resize smart +64'
shift-minus = 'resize smart -128'
shift-equal = 'resize smart +128'

#
# Other
#

shift-r = ['flatten-workspace-tree', 'mode alt'] # reset layout
#s = ['layout sticky tiling', 'mode alt'] # sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
# Toggle Maximize window
m = ['fullscreen']
# Float window
f = ['layout floating']
# Tile window
t = ['layout tiling']

#
# Modes
#

# See: https://nikitabobko.github.io/AeroSpace/commands#mode
r =  'mode resize'
semicolon = 'mode spacial'
w = 'mode workspace'
a = 'mode edit-workspace'

#
# Resize Mode
#

[mode.resize.binding]
# ctrl-alt-cmd-space = ['mode binding']
space = 'mode main'
esc = 'mode alt'
r = 'mode alt'
h = ['resize width -64']
j = ['resize height -64']
k = ['resize height +64']
l = ['resize width +64']
shift-h = ['resize width -8']
shift-j = ['resize height -8']
shift-k = ['resize height +8']
shift-l = ['resize width +8']

[mode.spacial.binding]
# ctrl-alt-cmd-space = ['mode special']
space = 'mode main'
esc = 'mode alt'
h = ['join-with left', 'mode alt']
j = ['join-with down', 'mode alt']
k = ['join-with up', 'mode alt']
l = ['join-with right', 'mode alt']

[mode.workspace.binding]
# ctrl-alt-cmd-space = ['mode workspace']
space = 'mode main'
esc = 'mode alt'
w = 'mode alt'
h = ['workspace prev', 'move-mouse window-force-center']
l = ['workspace next', 'move-mouse window-force-center']
j = ['focus-monitor next', 'move-mouse window-force-center']
k = ['focus-monitor prev', 'move-mouse window-force-center']
shift-h = ['move-node-to-workspace prev']
shift-l = ['move-node-to-workspace next']
shift-k = ['move-node-to-monitor prev']
shift-j = ['move-node-to-monitor next']

[mode.edit-workspace.binding]
    space = 'mode main'
    esc = 'mode alt' # See: https://nikitabobko.github.io/AeroSpace/commands#workspace
    1 = ['workspace 1', 'move-mouse window-force-center', 'mode main']
    2 = ['workspace 2', 'move-mouse window-force-center', 'mode main']
    3 = ['workspace 3', 'move-mouse window-force-center', 'mode main']
    4 = ['workspace 4', 'move-mouse window-force-center', 'mode main']
    5 = ['workspace 5', 'move-mouse window-force-center', 'mode main']
    6 = ['workspace 6', 'move-mouse window-force-center', 'mode main']
    7 = ['workspace 7', 'move-mouse window-force-center', 'mode main']
    8 = ['workspace 8', 'move-mouse window-force-center', 'mode main']
    9 = ['workspace 9', 'move-mouse window-force-center', 'mode main']
    0 = ['workspace 10', 'move-mouse window-force-center', 'mode main']
    a = ['workspace A', 'move-mouse window-force-center', 'mode main'] # In your config, you can drop workspace bindings that you don't need
    b = ['workspace B', 'move-mouse window-force-center', 'mode main']
    c = ['workspace C', 'move-mouse window-force-center', 'mode main']
    d = ['workspace D', 'move-mouse window-force-center', 'mode main']
    e = ['workspace E', 'move-mouse window-force-center', 'mode main']
    f = ['workspace F', 'move-mouse window-force-center', 'mode main']
    g = ['workspace G', 'move-mouse window-force-center', 'mode main']
    h = ['workspace H', 'move-mouse window-force-center', 'mode main']
    i = ['workspace I', 'move-mouse window-force-center', 'mode main']
    j = ['workspace J', 'move-mouse window-force-center', 'mode main']
    k = ['workspace K', 'move-mouse window-force-center', 'mode main']
    l = ['workspace L', 'move-mouse window-force-center', 'mode main']
    m = ['workspace M', 'move-mouse window-force-center', 'mode main']
    n = ['workspace N', 'move-mouse window-force-center', 'mode main']
    o = ['workspace O', 'move-mouse window-force-center', 'mode main']
    p = ['workspace P', 'move-mouse window-force-center', 'mode main']
    q = ['workspace Q', 'move-mouse window-force-center', 'mode main']
    r = ['workspace R', 'move-mouse window-force-center', 'mode main']
    s = ['workspace S', 'move-mouse window-force-center', 'mode main']
    t = ['workspace T', 'move-mouse window-force-center', 'mode main']
    u = ['workspace U', 'move-mouse window-force-center', 'mode main']
    v = ['workspace V', 'move-mouse window-force-center', 'mode main']
    w = ['workspace W', 'move-mouse window-force-center', 'mode main']
    x = ['workspace X', 'move-mouse window-force-center', 'mode main']
    y = ['workspace Y', 'move-mouse window-force-center', 'mode main']
    z = ['workspace Z', 'move-mouse window-force-center', 'mode main']

    # See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
    shift-1 = ['move-node-to-workspace 1', 'workspace 1', 'mode main']
    shift-2 = ['move-node-to-workspace 2', 'workspace 2', 'mode main']
    shift-3 = ['move-node-to-workspace 3', 'workspace 3', 'mode main']
    shift-4 = ['move-node-to-workspace 4', 'workspace 4', 'mode main']
    shift-5 = ['move-node-to-workspace 5', 'workspace 5', 'mode main']
    shift-6 = ['move-node-to-workspace 6', 'workspace 6', 'mode main']
    shift-7 = ['move-node-to-workspace 7', 'workspace 7', 'mode main']
    shift-8 = ['move-node-to-workspace 8', 'workspace 8', 'mode main']
    shift-9 = ['move-node-to-workspace 9', 'workspace 9', 'mode main']
    shift-0 = ['move-node-to-workspace 10', 'workspace 10', 'mode main']
    shift-a = ['move-node-to-workspace A', 'workspace A', 'mode main']
    shift-b = ['move-node-to-workspace B', 'workspace B', 'mode main']
    shift-c = ['move-node-to-workspace C', 'workspace C', 'mode main']
    shift-d = ['move-node-to-workspace D', 'workspace D', 'mode main']
    shift-e = ['move-node-to-workspace E', 'workspace E', 'mode main']
    shift-f = ['move-node-to-workspace F', 'workspace F', 'mode main']
    shift-g = ['move-node-to-workspace G', 'workspace G', 'mode main']
    shift-h = ['move-node-to-workspace H', 'workspace H', 'mode main']
    shift-i = ['move-node-to-workspace I', 'workspace I', 'mode main']
    shift-j = ['move-node-to-workspace J', 'workspace J', 'mode main']
    shift-k = ['move-node-to-workspace K', 'workspace K', 'mode main']
    shift-l = ['move-node-to-workspace L', 'workspace L', 'mode main']
    shift-m = ['move-node-to-workspace M', 'workspace M', 'mode main']
    shift-n = ['move-node-to-workspace N', 'workspace N', 'mode main']
    shift-o = ['move-node-to-workspace O', 'workspace O', 'mode main']
    shift-p = ['move-node-to-workspace P', 'workspace P', 'mode main']
    shift-q = ['move-node-to-workspace Q', 'workspace Q', 'mode main']
    shift-r = ['move-node-to-workspace R', 'workspace R', 'mode main']
    shift-s = ['move-node-to-workspace S', 'workspace S', 'mode main']
    shift-t = ['move-node-to-workspace T', 'workspace T', 'mode main']
    shift-u = ['move-node-to-workspace U', 'workspace U', 'mode main']
    shift-v = ['move-node-to-workspace V', 'workspace V', 'mode main']
    shift-w = ['move-node-to-workspace W', 'workspace W', 'mode main']
    shift-x = ['move-node-to-workspace X', 'workspace X', 'mode main']
    shift-y = ['move-node-to-workspace Y', 'workspace Y', 'mode main']
    shift-z = ['move-node-to-workspace Z', 'workspace Z', 'mode main']

#
# Application-specific configurations
#

# [[on-window-detected]]
# run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'Code - Insiders|Warp|Simulator'
run = ['layout tiling', 'move-node-to-workspace 2']

[[on-window-detected]]
if.app-name-regex-substring = 'Chrome|Firefox|Safari|Brave|Edge|Vivaldi|Opera'
run = ['layout tiling', 'move-node-to-workspace G']

[[on-window-detected]]
if.app-name-regex-substring = 'Cursor'
run = ['layout tiling', 'move-node-to-workspace U']

[[on-window-detected]]
if.app-name-regex-substring = 'Xcode'
run = ['layout tiling', 'move-node-to-workspace X']

[[on-window-detected]]
if.app-name-regex-substring = 'Finder'
run = ['layout floating', 'move-node-to-workspace T']